### ISSUE TITLE
Breaks with Joomla Convention

### ISSUE THREAD

**Issue by AlexBachmann** [Joomla-Ajax-Interface/component#21]
Hi Matt,

first of all, thank you for this great component. I tried it out, and I found this issue:

If you have a module, which name is a composite of two parts, it is the Joomla convention to call the module mod_part1_part2 and the Helper class is named ModPart1Part2Helper. You can see this convention used in mod_articles_latest, mod_random_image and other modules of that sort.

The component translates the module name directly into the helper classname. Hence it looks for helper classes like ModPart1_part2Helper instead of ModPart1Part2Helper. This causes the extension to fail. I think this is an easy problem to fix. I would suggest to check if the first classname exists and if it does not exists, it checks for the other classname.

Best regards,
Alex

**Comment by betweenbrain** [comment]
Hello Alex,

I'm happy to hear that it's been helpful. Thank you for the detailed explanation of the issue. I understand the situation and will take a look at your pull request as soon as possible.

**Comment by betweenbrain** [comment]
Resolved via 3d0af80
