### ISSUE TITLE
JRepsonseJSON

### ISSUE THREAD

**Issue by wilsonge** [Joomla-Ajax-Interface/component#24]
So if we're moving to this in Joomla 3.x - then would it be possible to modify the way we're sending back the data in J1.5 and 2.5 in line with this class. returning the data in a repsonse.data, a response.sucess which returns true or false, (although for this I guess we need to tap into JError for J1.5/2.5).

There's a nice doc page here outlining it's features http://docs.joomla.org/JSON_Responses_with_JResponseJson

Don't have any code to hand (yet) - but would be useful to still be able to support J2.5 and 3.x

**Comment by betweenbrain** [comment]
Definitely. My intention is to back-port as many of the developments from the version in core to the 2.5 and 1.5 versions. This may even include abstracting JResponseJson. I also like the way that exceptions have been proposed. I'd suggest we wait until 3.2 beta, or even better, 3.2 RC, to give things time to settle.

**Comment by wilsonge** [comment]
Are we happy to port over our own version JResponseJson to do this @betweenbrain . I'm finally got back to my module that I want to support on 3.x and 2.5 :P

**Comment by betweenbrain** [comment]
I have no objections :smile:

**Comment by wilsonge** [comment]
Closing in favour of #39
