### ISSUE TITLE
One version for 1.5 and 2.5

### ISSUE THREAD

**Issue by betweenbrain** [Joomla-Ajax-Interface/component#27]
@wilsonge I've just pushed some changes to https://github.com/Joomla-Ajax-Interface/component/tree/1.5-develop and I see no reason why we can't use that as a single version for 1.5 and 2.5. Thoughts?

**Comment by wilsonge** [comment]
Just had a quick flick through the code and it looks fine to me. I'll try and do some more detailed testing early next week :)

**Comment by betweenbrain** [comment]
I'm going to take another pass at this and push it to https://github.com/Joomla-Ajax-Interface/component/tree/develop, with all the proper documentation changes, if everythign looks good. I'll create a PR to merge to master for one final check.

**Comment by wilsonge** [comment]
OK :) I was gonna test it last night but ended up going through J3.2.1 instead. If you're gonna take another shot at it I'll leave testing for another day then

**Comment by betweenbrain** [comment]
Great. It's already to go actually, and PR is at https://github.com/Joomla-Ajax-Interface/component/pull/28. It's in the develop branch if you want to take it for a spin.

**Comment by wilsonge** [comment]
Sorry just realised I didn't reply to this - it worked nicely in 2.5 - although haven't tested it in 1.5

**Comment by betweenbrain** [comment]
Thanks for testing, and no worries about responding. It should be fine in
both 1.5 and 2.5. I had successfully tested this on both 1.5 and 2.5 prior
to the PR and then another round before merging it. I guess we'll see...

Best,

Matt Thomas
@betweenbrain
http://matt-thomas.me/
http://betweenbrain.com/
https://github.com/betweenbrain

**Comment by wilsonge** [comment]
Closing as we've had no complaints :P

**Comment by betweenbrain** [comment]
:+1:
