### ISSUE TITLE
PHP notice: Undefined variable: parts in ajax response

### ISSUE THREAD

**Issue by wilsonge** [Joomla-Ajax-Interface/component#31]
See https://github.com/joomla/joomla-cms/pull/3077

**Comment by betweenbrain** [comment]
Thanks!

**Comment by betweenbrain** [comment]
Just to clarify, I think that issue was / is already fixed. Nothing needed from us, correct?

**Comment by wilsonge** [comment]
Correct :) Closing this down

**Comment by betweenbrain** [comment]
Thanks!

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/
