### ISSUE TITLE
PLEASE put it in the JED!

### ISSUE THREAD

**Issue by stutteringp0et** [Joomla-Ajax-Interface/component#33]
Our interaction in the Joomla CMS issues list reminded me of a request I wanted to make (and have made in the Joomla forums, but I don't think you saw it).

Having com_ajax in 3.x is great - but not having it in 2.5 makes things difficult when considering rewriting some of my extensions to use it.  I'd love to use it, but I don't want to have 2 separate versions - one for 3.x using com_ajax and another for 2.5 using a shoehorned method.

I just don't think users will install from github as readily as they will from a link in the JED.

If you can put this in the JED, I can rewrite my extensions to use it and require 2.5 users to install your extension first.  

Please consider it.

**Comment by wilsonge** [comment]
@betweenbrain it's a good call. I'd support it!

**Comment by betweenbrain** [comment]
Agreed!

**Comment by stutteringp0et** [comment]
That was easy.  I may as well start rewriting now!

**Comment by stutteringp0et** [comment]
I've started a rewrite of my most popular extension.  I hope to give the first of many 5 star reviews when this hits the JED.

Should I close this?  It isn't really a proper issue (thanks for indulging me though)

**Comment by betweenbrain** [comment]
That would be great for you to be the first 5 star review.

Please keep this issue open. One of us will close it when it has been
listed.

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by betweenbrain** [comment]
I have submitted it to the JED and will keep this issue updated on the progress.

**Comment by betweenbrain** [comment]
Just added http://extensions.joomla.org/extensions/core-enhancements/coding-a-scripts-integration

Thanks!
