### ISSUE TITLE
Installing the component gives a menu item

### ISSUE THREAD

**Issue by wilsonge** [Joomla-Ajax-Interface/component#41]
Which of course whitescreens as we don't have any html output. I guess we need to add a script file to remove the component from the backend menu

**Comment by betweenbrain** [comment]
Hmmm... there was actually a post install script somewhere, in some
version, that did just that. I'll try to recall where it is.

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by wilsonge** [comment]
Yes I remember us having that at one point. But seems to have vanished from the github repo :/

**Comment by wilsonge** [comment]
https://github.com/Joomla-Ajax-Interface/component/tree/6cad143467975328f07b89fdff7f13601f6604eb In this commit the script exists

https://github.com/Joomla-Ajax-Interface/component/commit/c77345e1bf094efff1f3ae5625130ce3998a0f4a and in this commit (next one in the history) it's gone (i guess some rebase went wrong somewhere as it's not showing in the diffs??)

Do we just readd this script file? https://github.com/Joomla-Ajax-Interface/component/blob/6cad143467975328f07b89fdff7f13601f6604eb/script.php

**Comment by betweenbrain** [comment]
That works for me. Thanks for digging into it!

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by wilsonge** [comment]
https://github.com/Joomla-Ajax-Interface/component/pull/43 it got done :P But looking at it it's using JDatabaseQuery which means I guess this doesn't work on Joomla 1.5? How big an issue is this?
